# Generated by Django 5.1.1 on 2024-09-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("instructor", models.CharField(max_length=100)),
                ("issue_date", models.DateField(auto_now_add=True)),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=12, unique=True),
                ),
                ("qr_code", models.ImageField(blank=True, upload_to="qr_codes/")),
            ],
        ),
    ]
