# Generated by Django 5.1.1 on 2024-09-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_number",
            field=models.CharField(
                blank=True, editable=False, max_length=12, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="certificate",
            name="qr_code",
            field=models.ImageField(blank=True, editable=False, upload_to="qr_codes/"),
        ),
    ]
