# Generated by Django 5.1.1 on 2024-09-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0002_alter_certificate_certificate_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="certificates/pdf"),
        ),
    ]
