# Generated by Django 5.1.1 on 2024-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificate", "0003_certificate_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="certificates/png"),
        ),
    ]
